# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e33fd09e26ab397a6c8feeef98329a7fc012cb8da4716b660e35788a0767e789a5df8774fc79173244354314c6ac7fa3ae713524df30af143d0e6622e30deea

test:
  secret_key_base: ab6b78aa463bcbe3e8af83509924e5175b287813857db5b77f78fa2664e04d9771e13436f001323b8395a45ad7e48010823c4550ad399f1b637ae01af276d13c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
